version: '3.8'

services:
  support-plugin:
    build:
      context: .
      dockerfile: Dockerfile
    # image: support-plugin:latest
    ports:
      - "8888:8888"
    environment:
      - DOOTASK_URL="http://nginx"
      - DOOTASK_WEBHOOK=http://nginx/api/dialog/msg/sendtext
      - DOOTASK_VERSION="1.0.0"
    volumes:
      - ./docker/logs:/root/logs
    restart: unless-stopped
    networks:
      - support-plugin-network

networks:
  support-plugin-network:
    driver: bridge